//! Bakes `student_export.json` into the contract as constants.
//!
//! The build refuses to produce a contract unless:
//!   * the export's versions are the ones this engine implements,
//!   * keccak256(canonical export) equals the export's own `weightsHash`
//!     (so the hash the contract reports is recomputed, never trusted),
//!   * no accumulator or requantization product can overflow i64 for ANY
//!     in-range input (checked from the weights, worst case),
//!   * the certified domain lies inside the normalization ranges.
//!
//! Model selection: env `PRICER_MODEL_DIR` (default `../../model/k1-r1`, the
//! K1 round-1 student; `../../model/synthetic` is the toy model).

use serde_json::Value;
use std::{env, fmt::Write as _, fs, path::PathBuf};
use tiny_keccak::{Hasher, Keccak};

const EXPORT_FORMAT_VERSION: u64 = 2;
const FEATURE_SPEC_VERSION: u64 = 1;

/// Must equal PricerInputs (NoteQuoter.sol) and pricer_quant.FIELDS.
const FIELDS: [&str; 10] = [
    "spotBpsOfInitial",
    "distToKnockInBps",
    "volBpsAnnual",
    "kiBarrierBps",
    "acBarrierBps",
    "couponBpsPerPeriod",
    "timeToMaturitySecs",
    "timeToNextObsSecs",
    "observationsRemaining",
    "flags",
];

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let model_dir = env::var("PRICER_MODEL_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest.join("../../model/k1-r1"));
    let model_dir = fs::canonicalize(&model_dir)
        .unwrap_or_else(|e| panic!("model dir {}: {e}", model_dir.display()));
    let export_path = model_dir.join("student_export.json");
    println!("cargo:rerun-if-env-changed=PRICER_MODEL_DIR");
    println!("cargo:rerun-if-changed={}", export_path.display());
    println!("cargo:rustc-env=PRICER_MODEL_DIR={}", model_dir.display());

    let text = fs::read_to_string(&export_path).expect("read student_export.json");
    let export: Value = serde_json::from_str(&text).expect("parse student_export.json");

    assert_eq!(export["exportFormatVersion"].as_u64(), Some(EXPORT_FORMAT_VERSION), "exportFormatVersion");
    assert_eq!(export["featureSpecVersion"].as_u64(), Some(FEATURE_SPEC_VERSION), "featureSpecVersion");

    // --- hash pin -----------------------------------------------------------
    let stated = export["weightsHash"].as_str().expect("weightsHash");
    let mut blanked = export.clone();
    blanked["weightsHash"] = Value::String("0x".into());
    let mut canon = String::new();
    canonical(&blanked, &mut canon);
    let mut k = Keccak::v256();
    k.update(canon.as_bytes());
    let mut digest = [0u8; 32];
    k.finalize(&mut digest);
    let computed = format!("0x{}", hex(&digest));
    assert_eq!(stated, computed, "weightsHash does not match canonical export");

    // --- quantization parameters -------------------------------------------
    let wbits = export["quantization"]["weightBits"].as_u64().expect("weightBits");
    let abits = export["quantization"]["activationBits"].as_u64().expect("activationBits");
    assert!(wbits == 8 || wbits == 16, "weightBits must be 8 or 16");
    assert!((8..=16).contains(&abits), "activationBits must be 8..=16");
    let qmax: i128 = (1 << (abits - 1)) - 1;

    // --- feature ranges ------------------------------------------------------
    let norm = export["featureNormalization"].as_array().expect("featureNormalization");
    assert_eq!(norm.len(), FIELDS.len(), "feature count");
    let mut mins = Vec::new();
    let mut maxs = Vec::new();
    for (f, name) in norm.iter().zip(FIELDS) {
        assert_eq!(f["name"].as_str(), Some(name), "feature order");
        let (lo, hi) = (f["min"].as_i64().unwrap(), f["max"].as_i64().unwrap());
        assert!(lo < hi, "{name}: empty range");
        mins.push(lo);
        maxs.push(hi);
    }

    let mut out = String::new();
    writeln!(out, "// @generated by build.rs from {} — do not edit", export_path.display()).unwrap();
    writeln!(out, "pub const WEIGHTS_HASH: [u8; 32] = {digest:?};").unwrap();
    writeln!(out, "pub const QMAX: i64 = {qmax};").unwrap();
    writeln!(out, "pub const FIELD_MIN: [i64; {}] = {mins:?};", mins.len()).unwrap();
    writeln!(out, "pub const FIELD_MAX: [i64; {}] = {maxs:?};", maxs.len()).unwrap();

    // --- certified domain (what the model accepts; a subset of the above) -----
    let dom = &export["certifiedDomain"];
    let ranges = dom["ranges"].as_array().expect("certifiedDomain.ranges");
    assert_eq!(ranges.len(), FIELDS.len(), "certified range count");
    let mut dmins = Vec::new();
    let mut dmaxs = Vec::new();
    for (i, (r, name)) in ranges.iter().zip(FIELDS).enumerate() {
        assert_eq!(r["name"].as_str(), Some(name), "certified range order");
        let (lo, hi) = (r["min"].as_i64().unwrap(), r["max"].as_i64().unwrap());
        assert!(mins[i] <= lo && lo <= hi && hi <= maxs[i], "{name}: certified range outside normalization");
        dmins.push(lo);
        dmaxs.push(hi);
    }
    let check_dist = dom["consistency"]["distToKnockIn"].as_bool().expect("consistency.distToKnockIn");
    let obs_interval = dom["consistency"]["observationIntervalSecs"].as_i64().expect("observationIntervalSecs");
    assert!(obs_interval >= 0, "observationIntervalSecs");
    let mut exclusions = Vec::new();
    for ex in dom["exclusions"].as_array().expect("certifiedDomain.exclusions") {
        let bounds: Vec<String> = ex["bounds"]
            .as_array()
            .unwrap()
            .iter()
            .map(|b| {
                let f = FIELDS.iter().position(|n| Some(*n) == b["field"].as_str()).expect("exclusion field");
                let (lo, hi) = (b["min"].as_i64().unwrap(), b["max"].as_i64().unwrap());
                assert!(lo <= hi, "exclusion bound");
                format!("({f}, {lo}, {hi})")
            })
            .collect();
        assert!(!bounds.is_empty(), "empty exclusion excludes everything");
        exclusions.push(format!("&[{}]", bounds.join(", ")));
    }
    writeln!(out, "pub const DOMAIN_MIN: [i64; {}] = {dmins:?};", dmins.len()).unwrap();
    writeln!(out, "pub const DOMAIN_MAX: [i64; {}] = {dmaxs:?};", dmaxs.len()).unwrap();
    writeln!(out, "pub const CHECK_DIST: bool = {check_dist};").unwrap();
    writeln!(out, "pub const OBS_INTERVAL: i64 = {obs_interval};").unwrap();
    writeln!(out, "pub static EXCLUSIONS: &[&[(usize, i64, i64)]] = &[{}];", exclusions.join(", ")).unwrap();

    // --- layers ----------------------------------------------------------------
    let arch = export["architecture"]["layers"].as_array().expect("architecture.layers");
    let layers = export["layers"].as_array().expect("layers");
    assert_eq!(arch.len(), layers.len(), "architecture/layers length");
    assert!(arch.len() >= 2, "need at least one hidden layer");
    assert_eq!(export["architecture"]["inputDim"].as_u64(), Some(FIELDS.len() as u64));

    let mut prev = FIELDS.len();
    let mut max_width = prev;
    let mut in_bound: i128 = qmax; // worst-case |input| of the current layer
    let mut layer_refs = Vec::new();
    for (l, (spec, layer)) in arch.iter().zip(layers).enumerate() {
        let (ind, outd) = (spec["in"].as_u64().unwrap() as usize, spec["out"].as_u64().unwrap() as usize);
        let is_head = l == arch.len() - 1;
        assert_eq!(ind, prev, "layer {l}: in != previous out");
        assert_eq!(
            spec["activation"].as_str(),
            Some(if is_head { "linear" } else { "relu" }),
            "layer {l}: activation"
        );
        let w = decode_weights(layer["weightsHex"].as_str().unwrap(), wbits);
        assert_eq!(w.len(), ind * outd, "layer {l}: weight count");
        let bias: Vec<i64> = layer["bias"].as_array().unwrap().iter().map(|v| v.as_i64().unwrap()).collect();
        assert_eq!(bias.len(), outd, "layer {l}: bias count");

        // overflow proof: |acc_i| <= sum_j |w_ij| * in_bound + |b_i|
        let acc_bound: Vec<i128> = (0..outd)
            .map(|i| {
                w[i * ind..(i + 1) * ind].iter().map(|&x| (x as i128).abs()).sum::<i128>() * in_bound
                    + (bias[i] as i128).abs()
            })
            .collect();

        let (mult, shift): (Vec<i64>, Vec<u32>) = if is_head {
            assert_eq!(outd, 1, "head must have one output");
            let o = &export["output"];
            (vec![o["multiplierQ16"].as_i64().unwrap()], vec![(16 + o["shift"].as_i64().unwrap()) as u32])
        } else {
            let m = layer["requantMultiplierQ16"].as_array().unwrap();
            let s = layer["requantShift"].as_array().unwrap();
            assert!(m.len() == outd && s.len() == outd, "layer {l}: requant count");
            (
                m.iter().map(|v| v.as_i64().unwrap()).collect(),
                s.iter().map(|v| (16 + v.as_i64().unwrap()) as u32).collect(),
            )
        };
        for i in 0..outd {
            assert!((1..=62).contains(&shift[i]), "layer {l}/{i}: total shift out of range");
            assert!((1..65536).contains(&mult[i]), "layer {l}/{i}: multiplier out of range");
            let prod = acc_bound[i] * mult[i] as i128 + (1i128 << (shift[i] - 1));
            assert!(prod < i64::MAX as i128, "layer {l}/{i}: i64 overflow possible");
        }

        writeln!(out, "static W{l}: [i16; {}] = {w:?};", w.len()).unwrap();
        writeln!(out, "static B{l}: [i64; {outd}] = {bias:?};").unwrap();
        writeln!(out, "static M{l}: [i64; {outd}] = {mult:?};").unwrap();
        writeln!(out, "static S{l}: [u32; {outd}] = {shift:?};").unwrap();
        layer_refs.push(format!(
            "Layer {{ inputs: {ind}, outputs: {outd}, w: &W{l}, b: &B{l}, m: &M{l}, s: &S{l} }}"
        ));
        prev = outd;
        max_width = max_width.max(outd);
        in_bound = qmax + 1; // hidden activations saturate to [-qmax-1, qmax]
    }
    let offset = export["output"]["offsetBps"].as_i64().expect("output.offsetBps");
    writeln!(out, "pub const OUTPUT_OFFSET_BPS: i64 = {offset};").unwrap();
    writeln!(out, "pub const MAX_WIDTH: usize = {max_width};").unwrap();
    writeln!(out, "pub static LAYERS: [Layer; {}] = [{}];", layer_refs.len(), layer_refs.join(", ")).unwrap();

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("model.rs");
    fs::write(dest, out).unwrap();
}

fn decode_weights(h: &str, bits: u64) -> Vec<i16> {
    let bytes: Vec<u8> = (0..h.len() - 2)
        .step_by(2)
        .map(|i| u8::from_str_radix(&h[2 + i..4 + i], 16).unwrap())
        .collect();
    match bits {
        8 => bytes.iter().map(|&b| b as i8 as i16).collect(),
        _ => bytes.chunks_exact(2).map(|c| i16::from_le_bytes([c[0], c[1]])).collect(),
    }
}

/// Canonical JSON: keys sorted at every depth, no whitespace. Floats are
/// rejected, which makes this byte-identical to Python's
/// `json.dumps(sort_keys=True, separators=(",", ":"), ensure_ascii=False)`.
fn canonical(v: &Value, out: &mut String) {
    match v {
        Value::Null => out.push_str("null"),
        Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        Value::Number(n) => {
            assert!(n.is_i64() || n.is_u64(), "float in export: {n}");
            write!(out, "{n}").unwrap();
        }
        Value::String(s) => out.push_str(&serde_json::to_string(s).unwrap()),
        Value::Array(a) => {
            out.push('[');
            for (i, x) in a.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                canonical(x, out);
            }
            out.push(']');
        }
        Value::Object(o) => {
            let mut keys: Vec<&String> = o.keys().collect();
            keys.sort();
            out.push('{');
            for (i, k) in keys.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                out.push_str(&serde_json::to_string(k).unwrap());
                out.push(':');
                canonical(&o[*k], out);
            }
            out.push('}');
        }
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}
